/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardrobeRouteImport } from './routes/wardrobe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRightsRouteImport } from './routes/privacy-rights'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const WardrobeRoute = WardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRightsRoute = PrivacyRightsRouteImport.update({
  id: '/privacy-rights',
  path: '/privacy-rights',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-rights': typeof PrivacyRightsRoute
  '/profile': typeof ProfileRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/wardrobe': typeof WardrobeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-rights': typeof PrivacyRightsRoute
  '/profile': typeof ProfileRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/wardrobe': typeof WardrobeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/dpa': typeof DpaRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-rights': typeof PrivacyRightsRoute
  '/profile': typeof ProfileRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/wardrobe': typeof WardrobeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookies'
    | '/dpa'
    | '/insights'
    | '/onboarding'
    | '/planner'
    | '/pricing'
    | '/privacy'
    | '/privacy-rights'
    | '/profile'
    | '/refunds'
    | '/terms'
    | '/wardrobe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookies'
    | '/dpa'
    | '/insights'
    | '/onboarding'
    | '/planner'
    | '/pricing'
    | '/privacy'
    | '/privacy-rights'
    | '/profile'
    | '/refunds'
    | '/terms'
    | '/wardrobe'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cookies'
    | '/dpa'
    | '/insights'
    | '/onboarding'
    | '/planner'
    | '/pricing'
    | '/privacy'
    | '/privacy-rights'
    | '/profile'
    | '/refunds'
    | '/terms'
    | '/wardrobe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  DpaRoute: typeof DpaRoute
  InsightsRoute: typeof InsightsRoute
  OnboardingRoute: typeof OnboardingRoute
  PlannerRoute: typeof PlannerRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyRightsRoute: typeof PrivacyRightsRoute
  ProfileRoute: typeof ProfileRoute
  RefundsRoute: typeof RefundsRoute
  TermsRoute: typeof TermsRoute
  WardrobeRoute: typeof WardrobeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wardrobe': {
      id: '/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof WardrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-rights': {
      id: '/privacy-rights'
      path: '/privacy-rights'
      fullPath: '/privacy-rights'
      preLoaderRoute: typeof PrivacyRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  DpaRoute: DpaRoute,
  InsightsRoute: InsightsRoute,
  OnboardingRoute: OnboardingRoute,
  PlannerRoute: PlannerRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyRightsRoute: PrivacyRightsRoute,
  ProfileRoute: ProfileRoute,
  RefundsRoute: RefundsRoute,
  TermsRoute: TermsRoute,
  WardrobeRoute: WardrobeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
